#ifndef HSA_SIGNAL_CL_H 
#define HSA_SIGNAL_CL_H 

unsigned long signal_ld_rlx_b64_sig64(unsigned long signalHandle);
unsigned long signal_ld_scacq_b64_sig64(unsigned long signalHandle);
void signalnoret_st_rlx_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_st_screl_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_and_rlx_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_and_rlx_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_and_scacq_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_and_scacq_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_and_screl_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_and_screl_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_and_scar_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_and_scar_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_or_rlx_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_or_rlx_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_or_scacq_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_or_scacq_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_or_screl_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_or_screl_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_or_scar_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_or_scar_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_xor_rlx_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_xor_rlx_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_xor_scacq_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_xor_scacq_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_xor_screl_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_xor_screl_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_xor_scar_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_xor_scar_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_exch_rlx_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_exch_scacq_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_exch_screl_b64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_exch_scar_b64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_add_rlx_u64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_add_rlx_u64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_add_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_add_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_add_scacq_u64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_add_scacq_u64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_add_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_add_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_add_screl_u64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_add_screl_u64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_add_screl_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_add_screl_s64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_add_scar_u64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_add_scar_u64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_add_scar_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_add_scar_s64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_sub_rlx_u64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_sub_rlx_u64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_sub_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_sub_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_sub_scacq_u64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_sub_scacq_u64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_sub_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_sub_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_sub_screl_u64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_sub_screl_u64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_sub_screl_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_sub_screl_s64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_sub_scar_u64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_sub_scar_u64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_sub_scar_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_sub_scar_s64_sig64(unsigned long signalHandle, unsigned long src0);
void signalnoret_cas_rlx_b64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_cas_rlx_b64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
void signalnoret_cas_scacq_b64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_cas_scacq_b64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
void signalnoret_cas_screl_b64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_cas_screl_b64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
void signalnoret_cas_scar_b64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_cas_scar_b64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_wait_eq_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_wait_eq_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_wait_ne_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_wait_ne_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_wait_lt_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_wait_lt_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_wait_gte_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_wait_gte_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0);
unsigned long signal_waittimeout_eq_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_waittimeout_eq_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_waittimeout_ne_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_waittimeout_ne_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_waittimeout_lt_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_waittimeout_lt_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_waittimeout_gte_rlx_s64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);
unsigned long signal_waittimeout_gte_scacq_s64_sig64(unsigned long signalHandle, unsigned long src0, unsigned long src1);

#endif
